# Generated by Django 3.0.5 on 2020-05-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('author', models.CharField(default='', max_length=200)),
                ('body', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
